# Generated by Django 4.1.6 on 2023-02-11 23:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_author_first_name_alter_author_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.FileField(upload_to='music/images')),
            ],
        ),
        migrations.RemoveField(
            model_name='author',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='country',
            name='city',
        ),
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, max_length=40, null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.country')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.city'),
        ),
        migrations.AddField(
            model_name='song',
            name='cover',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.cover'),
        ),
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.cover'),
        ),
    ]
