# Generated by Django 4.1.6 on 2023-02-11 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_cover_remove_author_origin_remove_country_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cover',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.city'),
        ),
    ]
