# Generated by Django 4.1.6 on 2023-02-12 00:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_cover_title_alter_author_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
