# Generated by Django 4.1.6 on 2023-02-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_cover_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='lyric',
            field=models.TextField(blank=True, null=True),
        ),
    ]
