# Generated by Django 4.1.6 on 2023-02-12 16:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(max_length=300)),
                ('download', models.BooleanField(default=False)),
                ('files', models.FileField(blank=True, null=True, upload_to='bookmark/sites')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField()),
                ('cover', models.FileField(blank=True, null=True, upload_to='bookmark/images')),
            ],
        ),
    ]
