# Generated by Django 4.1.6 on 2023-02-12 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0002_rename_tags_tag_bookmark_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='date_time',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to='bookmark/images'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookmark.tag'),
        ),
    ]
